[package]
name = "bevtask"
version = "0.1.0"
edition = "2021"

[[test]]
name = "all"
path = "tests/entry_point.rs"

[[example]]
name = "until_move"
path = "examples/until_move.rs"

[dependencies]
bevy = {version = "0.11.3", default-features = false }
async-trait = "0.1.73"
futures-lite = "1.13.0"
futures = "0.3.28"

[features]
default = ["update"]
first = []
pre_update = []
state_transition = []
update = []
fixed_update = []
post_update = []
last = []


[dev-dependencies]
bevy = "0.11.3"
trybuild2 = "1.1.0"
bevtask = {path = ".", version = "0.1", features = ["pre_update"]}
reqwest = "0.11.22"
