[package]
name = "bevy_async_system"
version = "0.1.0"
edition = "2021"


[[example]]
name = "cancel_task"
path = "examples/cancel/cancel_task.rs"

[[example]]
name = "cancel_system"
path = "examples/cancel/cancel_system.rs"

[[example]]
name = "delay_time_and_frames"
path = "examples/delay/delay_time_and_frames.rs"

[[example]]
name = "move_shape"
path = "examples/wait/move_shape.rs"

[[example]]
name = "wait_for_audio_playback_to_finish"
path = "examples/wait/wait_for_audio_playback_to_finish.rs"



[dependencies]
bevy = {version = "0.11.3", default-features = false }
async-trait = "0.1.73"
futures-lite = "1.13.0"
futures = "0.3.28"
async-compat = "0.2.2"


[features]
default = ["update"]
first = []
pre_update = []
state_transition = []
update = []
fixed_update = []
post_update = []
last = []


[dev-dependencies]
bevy = "0.11.3"
trybuild2 = "1.1.0"
bevy_async_system = {path = ".", version = "0.1", features = ["pre_update"]}
reqwest = "0.11.22"
bevy_framepace = "0.13.3"