[package]
name = "bevy_async_system"
version = "0.1.0"
edition = "2021"
authors = ["elm"]
categories = ["asynchronous", "game-development"]
description = "Provides the ability to wait for game status asynchronously."
keywords = ["game", "gamedev", "bevy", "async"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/elmtw/bevy_async_system"


[[example]]
name = "reqwest"
path = "examples/reqwest.rs"


[[example]]
name = "despawn_task"
path = "examples/cancel/despawn_task.rs"


[[example]]
name = "cancel_system"
path = "examples/cancel/cancel_system.rs"

[[example]]
name = "delay_time_and_frames"
path = "examples/delay/delay_time_and_frames.rs"

[[example]]
name = "move_shape"
path = "examples/wait/move_shape.rs"

[[example]]
name = "wait_for_audio_playback_to_finish"
path = "examples/wait/wait_for_audio_playback_to_finish.rs"

[[example]]
name = "join_all"
path = "examples/join_handle/join_all.rs"

[[example]]
name = "once"
path = "examples/once.rs"


[[example]]
name = "repeat"
path = "examples/repeat.rs"


[dependencies]
bevy = { version = "0.11.3", default-features = false }
async-trait = "0.1.73"
futures-lite = "1.13.0"
futures = "0.3.28"
async-compat = "0.2.2"


[dev-dependencies]
bevy = "0.11.3"
trybuild2 = "1.1.0"
bevy_async_system = { path = "." }
reqwest = "0.11.22"
bevy_framepace = "0.13.3"
bevy-inspector-egui = "0.20.0"